### ISSUE TITLE
Great Idea, but can't get it to work on the Mac.

### ISSUE THREAD

**Issue by davidfkane** [dbarenholz/outlook-to-obsidian#1]
This is such a great idea but I have no idea how to configure this on the Mac.

Outlook: Version 16.60 Mac
OS: Monterey Version 12.2.1
Model Name:	MacBook Pro
Model Identifier:	MacBookPro16,1
Processor Name:	8-Core Intel Core i9
Processor Speed:	2.3 GHz

<img width="321" alt="image" src="https://user-images.githubusercontent.com/3740123/163166190-01619eb5-13da-47ec-bee6-3d9d15428a7b.png">

**Comment by dbarenholz** [comment]
It's not functioning right now, so it makes sense that it doesn't work. I've been too busy with thesis and personal life to work on this, sorry!

**Comment by davidfkane** [comment]
Good luck with your Thesis. I don't have the Node skills to help on this, unfortunately.  👍🏻
